Repository okaneco/safe_unaligned_simd, pull requests merged in 2025-07, with the labels that each got.

#2 Prepare for initial `0.1.0` release
  README.md
  src/lib.rs
  src/x86_64.rs
Labels: documentation, update

#7 Add `nightly` feature for unstable functions
  .github/workflows/rust-ci.yml
  Cargo.toml
  src/x86/avx.rs
Labels: Actions/CI, Crate feature

#9 Fixup CI script
  .github/workflows/rust-ci.yml
  src/x86.rs
Labels: Actions/CI

#8 Abstractions around aarch64 neon loads and stores
  .github/workflows/rust-ci.yml
  Cargo.toml
  README.md
  src/aarch64.rs
  src/lib.rs
Labels: Actions/CI, A-aarch64

#11 Move `x86` cell functions to their own module
  README.md
  src/lib.rs
  src/x86.rs
  src/x86/avx.rs
  src/x86/cell.rs
  src/x86/cell/avx.rs
  src/x86/cell/sse2.rs
  src/x86/sse2.rs
Labels: A-x86/x86_64

#13 Small fixups to documentation and consistency
  .github/workflows/rust-ci.yml
  README.md
  src/aarch64.rs
  src/lib.rs
Labels: documentation, Actions/CI

#16 Add caching to CI jobs, compiletest job fixups
  .github/workflows/rust-ci.yml
  tests/assembly/x86/sse.rs
  tests/tests.rs
Labels: Actions/CI

#15 Implement generic load/store for `Cell` types of 16/32/64 bits for `x86`
  src/x86.rs
  src/x86/cell/sse2.rs
Labels: A-x86/x86_64, Tests, relnotes

#18 Prepare for `0.2` release, update README.md
  CHANGELOG.md
  README.md
  src/aarch64.rs
  src/lib.rs
  src/x86/cell.rs
Labels: documentation, update
